Walkthrough: Deployment 2
quintilesims/layer0-examples pull request #6
Opened 2017-04-07 23:55 UTC by tlake

2017-05-17 21:36 UTC, zpatrick requested changes

2017-05-17 21:36 UTC, zpatrick commented on iterative-walkthrough/deployment-3/guestbook-redis-consul/main.go
> +		return fireball.NewResponse(200, []byte(err.Error()), nil), nil
You can return errors in fireball: 
```
return fireball.NewResponse(200, []byte(err.Error()), nil), nil
```
can be: 
```
return nil, err
```

2017-05-18 00:17 UTC, zpatrick requested changes

2017-05-18 00:17 UTC, zpatrick commented on iterative-walkthrough/deployment-3/guestbook-redis-consul/main.go
> +type ConsulService struct {
A consul api package for go exists at: https://github.com/armon/consul-api

2017-05-22 16:36 UTC, tlake commented
Oh, woops - I didn't realize I still had this open PR when I started pushing deployment 3 stuff. I'll close this one now and start a proper deployment-2 PR. Once that finishes, I'll do one for the deployment-3 materials.

2017-05-22 16:36 UTC, closed without merging