Walkthrough: Generalize Guestbook Redis Lookup
quintilesims/layer0-examples pull request #9
Opened 2017-05-22 21:19 UTC by tlake

These changes should allow a user to pass in a `URL:PORT` string location of the redis loadbalancer to the Guestbook app within layer0.tf. If this value is set to `""`, the Guestbook app will use the Consul API to query for a service named 'redis' and create the string location from the call's result.

2017-05-22 22:25 UTC, diemonster requested changes

2017-05-22 22:25 UTC, diemonster commented on iterative-walkthrough/deployment-2/guestbook-redis/main.go
> +	"fmt"
[mega nit] these imports were changed because you are using `go import` rather than `gofmt` for auto formatting. I think we've generally landed on `gofmt` as the preferred formatter.

2017-05-22 22:25 UTC, diemonster commented on iterative-walkthrough/deployment-2/guestbook-redis/main.go
> +	redisAddress, err := getRedisAddress()
It seems like calling `getRedisAddress` is unnecessary in these various places if you instead ran `getRedisAddress` in main and mutated the `redis` connection params

2017-05-22 22:33 UTC, diemonster commented on iterative-walkthrough/deployment-2/guestbook-redis/main.go
> +	redisAddress, err := getRedisAddress()
Unless the `redis` service is intended to change connection details over time, in which case never mind

2017-05-23 16:43 UTC, tlake commented on iterative-walkthrough/deployment-2/guestbook-redis/main.go
> +	"fmt"
Interesting - running `gofmt -w` doesn't seem to introduce a change to the file.

2017-05-23 22:13 UTC, tlake commented on iterative-walkthrough/deployment-2/guestbook-redis/main.go
> +	redisAddress, err := getRedisAddress()
I think this will be fixed once @zpatrick merges his updates in.

2017-05-24 18:02 UTC, closed without merging